#! /bin/bash
### BEGIN INIT INFO
# Provides:         redis-server
# Required-Start:   $syslog
# Required-Stop:    $syslog
# Should-Start:     $local_fs
# Should-Stop:      $local_fs
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description:  redis-server - Persistent key-value db
# Description:        redis-server - Persistent key-value db
### END INIT INFO

DAEMON=/usr/local/redis/bin/redis-server
DAEMON_ARGS=/usr/local/redis/etc/redis.conf
NAME=redis-server
PIDFILE=/var/run/redis.pid

test -x ${DAEMON} || exit 0
test -x ${DAEMONBOOTSTRAP} || exit 0

set -e

case "$1" in
  start)
    echo -n "Starting $NAME: "
    touch ${PIDFILE}
    chown redis:redis ${PIDFILE}
    if start-stop-daemon --start --quiet --umask 007 --pidfile ${PIDFILE} --chuid redis:redis --exec ${DAEMON} -- ${DAEMON_ARGS}
    then
        echo "success"
    else
        echo "failed"
    fi
    ;;
  stop)
    echo -n "Stopping $NAME: "
    if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile ${PIDFILE} --exec ${DAEMON}
    then
        echo "success"
    else
        echo "failed"
    fi
    rm -f ${PIDFILE}
    ;;

  restart|force-reload)
    ${0} stop
    ${0} start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
